group 'com.lykhonis.imagecrop'
version '1.0-SNAPSHOT'

buildscript {
    ext {
        kotlin_version = '2.1.10'
        agp_version = '8.7.3'
    }
    repositories {
        gradlePluginPortal()
        mavenCentral()
        google()
    }
    dependencies {
        classpath "com.android.tools.build:gradle:$agp_version"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

rootProject.allprojects {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

apply plugin: 'com.android.library'

android {
    namespace "com.lykhonis.imagecrop"
    compileSdkVersion 35

    defaultConfig {
        minSdkVersion 21
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    lintOptions {
        disable 'InvalidPackage'
    }
}

dependencies {
    implementation 'androidx.exifinterface:exifinterface:1.0.0'
}
